name: skip-lib ci

on:
  push:
  schedule:
    - cron:  '0 11,21 * * *'
  workflow_dispatch:
  pull_request:

env:
  DEVELOPER_DIR: /Applications/Xcode_15.0.app/Contents/Developer

jobs:
  ci:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - run: swift test

